#--
# Copyright (c) 2009 Muriel Salvan (murielsalvan@users.sourceforge.net)
# Licensed under the terms specified in LICENSE file. No warranty is provided.
#++

# This file prepares a win32 distribution

# Require needed to generate the temporary ruby file that produces the executable
require 'tmpdir'

module RubyPackager

  class PlatformReleaser

    PLATFORM_DIR = File.dirname(__FILE__)

    # Check if the tools we will use are present
    #
    # Parameters:
    # * *iRootDir* (_String_): Root directory
    # * *iIncludeRuby* (_Boolean_): Do we include Ruby in the release ?
    # Return:
    # * _Boolean_: Are tools correctly useable ?
    def checkTools(iRootDir, iIncludeRuby)
      rSuccess = true

      if (iIncludeRuby)
        # We need allinoneruby
        if (Gem.find_files('allinoneruby').empty?)
          puts "!!! Need to have allinoneruby gem to release including Ruby."
          puts "!!! Please install allinoneruby gem (gem install allinoneruby)."
          rSuccess = false
        end
      end
      # Check that edicon is present
      if (!File.exists?("#{PLATFORM_DIR}/edicon/edicon.exe"))
        puts "!!! Need to have edicon.exe installed in #{PLATFORM_DIR}/edicon to set a Windows executable's icon."
        puts "!!! Please install edicon, part of Ocra Gem (gem install ocra), and copy from the Gem directory (ocra-1.1.1/share/ocra/edicon.exe) to #{PLATFORM_DIR}/edicon/edicon.exe."
        rSuccess = false
      end
      # Check that exerb is present
      if (!system('exerb.bat --version'))
        puts "!!! Need to have exerb installed in the system PATH to create a Windows executable."
        puts "!!! Please download and install exerb from http://exerb.sourceforge.jp/index.en.html"
        rSuccess = false
      end
      # Check that makensis is present
      if (!system('makensis /VERSION'))
        puts "!!! Need to have MakeNSIS installed in the system PATH to create installer."
        puts "!!! Please download and install MakeNSIS in the PATH from http://nsis.sourceforge.net/Main_Page"
        rSuccess = false
      end

      return rSuccess
    end

    # Create the binary.
    # This is called when the core library has been copied in the release directory.
    #
    # Parameters:
    # * *iRootDir* (_String_): Root directory
    # * *iReleaseDir* (_String_): Release directory
    # * *iIncludeRuby* (_Boolean_): Do we include Ruby in the release ?
    # * *iMainRBFile* (_String_): Name of the main .rb file to call at startup
    # * *iExeName* (_String_): Name of the executable to produce
    # * *iIconName* (_String_): Name of the executable icon (relative to root dir)
    # * *iTerminalApplication* (_Boolean_): Is the application intended to run in a terminal ?
    # Return:
    # * _Boolean_: Success ?
    def createBinary(iRootDir, iReleaseDir, iIncludeRuby, iMainRBFile, iExeName, iIconName, iTerminalApplication)
      rSuccess = true

      lBinSubDir = "Launch/#{RUBY_PLATFORM}/bin"
      lRubyBaseBinName = nil
      lRubyLaunchCmd = nil
      if (iTerminalApplication)
        lRubyBaseBinName = 'ruby'
        lRubyLaunchCmd = 'ruby'
      else
        lRubyBaseBinName = 'rubyw'
        lRubyLaunchCmd = 'start rubyw'
      end
      lBinName = "#{lRubyBaseBinName}-#{RUBY_VERSION}.exe"
      if (iIncludeRuby)
        # First create the binary containing all ruby
        lBinDir = "#{iReleaseDir}/#{lBinSubDir}"
        FileUtils::mkdir_p(lBinDir)
        lOldDir = Dir.getwd
        Dir.chdir(lBinDir)
        lCmd = nil
        if (iTerminalApplication)
          lCmd = "allinoneruby.bat #{lBinName}"
        else
          lCmd = "allinoneruby.bat --rubyw #{lBinName}"
        end
        rSuccess = system(lCmd)
        if (!rSuccess)
          puts "!!! Error while executing \"#{lCmd}\""
        end
        Dir.chdir(lOldDir)
      end
      if (rSuccess)
        # Then create the real executable
        # Generate the Ruby file that launches everything for Windows
        lTempFileName = "#{Dir.tmpdir}/EXE_#{RUBY_PLATFORM}_Gen.rb"
        File.open(lTempFileName, 'w') do |oFile|
          oFile << "
\#--
\# Copyright (c) 2009 Muriel Salvan (murielsalvan@users.sourceforge.net)
\# Licensed under the terms specified in LICENSE file. No warranty is provided.
\#++

\# This file is generated by RubyPackager for Windows.
\# This is a temporary file that should not exist anymore once the release has been done.

\# This file has to launch the correct binary. There can be several binaries dependending on the configuration.
\# This is the file that will be created as the executable to launch.

module RubyPackager

  \# Execute a shell command
  \#
  \# Parameters:
  \# * *iCmd* (_String_): The shell command to execute
  \# Return:
  \# * _Boolean_: Success ?
  def self.shellExecute(iCmd)
    puts \"> \#{iCmd}\"
    rSuccess = system(iCmd)

    if (!rSuccess)
      puts \"Error while executing '\#{iCmd}'\"
    end

    return rSuccess
  end

end

\# Test if Ruby is installed
lSuccess = false
lCurrentDir = Dir.getwd
if (system('#{lRubyBaseBinName} --version'))
  \# Launch directly
  puts \"Ruby found in environment. Using it directly.\"
  lSuccess = RubyPackager::shellExecute(\"#{lRubyLaunchCmd} -w \\\"\#{lCurrentDir}/#{iMainRBFile}\\\" \#{ARGV.join(' ')}\")
end
if (!lSuccess)
  \# Use allinoneruby
  puts \"Ruby not found in environment. Using shipped Ruby.\"
  lSuccess = RubyPackager::shellExecute(\"start \\\"Title\\\" \\\"\#{lCurrentDir}/#{lBinSubDir}/#{lBinName}\\\" \\\"\#{lCurrentDir}/#{iMainRBFile}\\\" \#{ARGV.join(' ')}\")
  if (!lSuccess)
    puts 'Unable to execute the application. Please reinstall it.'
    puts 'Hit enter to quit.'
    $stdin.gets
  end
end
"
        end
        lOldDir = Dir.getwd
        Dir.chdir(iReleaseDir)
        rSuccess = system("exerb.bat -o #{iExeName}.exe #{lTempFileName}")
        Dir.chdir(lOldDir)
        if (rSuccess)
          File.unlink(lTempFileName)
          # And set its icon
          rSuccess = system("#{PLATFORM_DIR}/edicon/edicon.exe #{iReleaseDir}/#{iExeName}.exe #{iRootDir}/#{iIconName}")
          if (!rSuccess)
            puts "!!! Error while executing \"#{PLATFORM_DIR}/edicon/edicon.exe #{iReleaseDir}/#{iExeName}.exe #{iRootDir}/#{iIconName}\""
          end
        else
          puts "!!! Error while executing \"exerb.bat -o #{iExeName}.exe #{lTempFileName}\""
        end
      end

      return rSuccess
    end

    # Create the installer with everything in the release directory.
    #
    # Parameters:
    # * *iRootDir* (_String_): The Root directory
    # * *iReleaseDir* (_String_): The release directory (all files to put in the installer are there)
    # * *iInstallerDir* (_String_): The directory where the installer has to be put
    # * *iVersion* (_String_): Release version
    # * *iNSIFileName* (_String_): Name of the NSI file
    # Return:
    # * _Boolean_: Success ?
    def createInstaller(iRootDir, iReleaseDir, iInstallerDir, iVersion, iNSIFileName, iExeName)
      rSuccess = system("makensis /DVERSION=#{iVersion} \"/DRELEASEDIR=#{iReleaseDir.gsub(/\//,'\\')}\" \"#{iRootDir.gsub(/\//,'\\')}\\#{iNSIFileName.gsub(/\//,'\\')}\"")

      if (rSuccess)
        lInstallerDir = File.dirname("#{iRootDir}/#{iNSIFileName}")
        FileUtils.mv("#{lInstallerDir}/setup.exe", "#{iInstallerDir}/#{iExeName}_#{iVersion}_setup.exe")
      end

      return rSuccess
    end

  end

end
